# Generated by Django 4.0.3 on 2022-04-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryt', '0005_alter_document_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='signed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='Mexico', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stylish_signature',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='text_signature',
            field=models.CharField(default='signature', max_length=100),
            preserve_default=False,
        ),
    ]
