# Generated by Django 4.0.3 on 2022-04-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryt', '0006_document_reason_document_signed_userprofile_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='document',
            name='location',
            field=models.CharField(default='Mexico', max_length=200),
        ),
    ]
