# Generated by Django 4.0.3 on 2022-04-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryt', '0007_remove_userprofile_location_document_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='signed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
