# Generated by Django 4.0.3 on 2022-04-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryt', '0008_alter_document_signed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='signed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
