# Generated by Django 4.0.3 on 2022-04-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryt', '0009_alter_document_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pem',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
