# Generated by Django 4.0.3 on 2022-04-21 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryt', '0012_alter_userprofile_p12_alter_userprofile_pem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='p12',
            new_name='private_key',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='pem',
            new_name='public_key',
        ),
    ]
