# Generated by Django 4.0.3 on 2022-04-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryt', '0014_alter_userprofile_text_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='signature',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
