# Generated by Django 4.0.3 on 2022-04-23 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryt', '0016_alter_document_document_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
