# Generated by Django 4.0.3 on 2022-04-23 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryt', '0019_alter_document_document_alter_document_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='stylish_signature',
        ),
    ]
