# Generated by Django 4.0.3 on 2022-04-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryt', '0020_remove_userprofile_stylish_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='hash',
            field=models.TextField(blank=True, null=True),
        ),
    ]
